package service;

import domain.Waffle;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class WaffleManager
{
    private Connection connection;
    private Statement statement;
    private PreparedStatement addWaffleStmt;
    private PreparedStatement deleteAllWafflesStmt;
    private PreparedStatement getAllWafflesStmt;

    private String url = "jdbc:hsqldb:file:/tmp/testdb;ifexists=false";
    private String createTableWaffle = "CREATE TABLE Waffle(id bigint GENERATED BY DEFAULT AS IDENTITY, type varchar(50), price DECIMAL, topping VARCHAR(20), sugar VARCHAR(20), cream VARCHAR(20), fruit VARCHAR(20))";

    public WaffleManager() {
        try {
            connection = DriverManager.getConnection(url, "SA", "");
            statement = connection.createStatement();

            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Waffle".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists)
                statement.executeUpdate(createTableWaffle);

            addWaffleStmt = connection.prepareStatement("INSERT INTO Waffle (type, price, topping, sugar, cream, fruit) VALUES (?, ?, ?, ?, ?, ?)");
            deleteAllWafflesStmt = connection.prepareStatement("DELETE FROM Waffle");
            getAllWafflesStmt = connection.prepareStatement("SELECT id, type, topping, sugar, cream, fruit FROM Waffle");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    Connection getConnection() {
        return connection;
    }
}
