package service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import domain.Waffle;

public class WaffleManager
{
    private Connection connection;
    private Statement statement;
	//    przypisanie x do y
    private PreparedStatement addWaffleStmt;
    private PreparedStatement deleteAllWafflesStmt;
    private PreparedStatement getAllWafflesStmt;
	private PreparedStatement ModifyTypeStmt;
	private PreparedStatement getWaffleByIdStmt;
	private PreparedStatement deleteWaffleStmt;
	//    pobranie x należących do y
	private PreparedStatement getWafflesFromOrderStmt;
	//    usunięcie x z y
	private PreparedStatement deleteWaffleFromOrderStmt;

    private String url = "jdbc:hsqldb:hsql://localhost/workdb";
    private String createTableWaffle = "CREATE TABLE Waffle(id bigint GENERATED BY DEFAULT AS IDENTITY, id_order bigint, type varchar(50), price DECIMAL(5,1), topping VARCHAR(20), sugar VARCHAR(20), cream VARCHAR(20), fruit VARCHAR(20), FOREIGN KEY (id_order) REFERENCES \"Order\"(id) ON DELETE CASCADE)";
	private String addForeignKey = "ALTER TABLE Waffle ADD FOREIGN KEY (id_order) REFERENCES \"Order\"(id)";

    public WaffleManager()
	{
        try
		{
            connection = DriverManager.getConnection(url);
            statement = connection.createStatement();

            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next())
			{
                if ("Waffle".equalsIgnoreCase(rs.getString("TABLE_NAME")))
				{
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists) {
				statement.executeUpdate(createTableWaffle);
				//statement.executeUpdate(addForeignKey);
			}

            addWaffleStmt = connection.prepareStatement("INSERT INTO Waffle (id_order, type, price, topping, sugar, cream, fruit) VALUES (?,?, ?, ?, ?, ?, ?)");
            deleteAllWafflesStmt = connection.prepareStatement("DELETE FROM Waffle");
            getAllWafflesStmt = connection.prepareStatement("SELECT id, price, type, topping, sugar, cream, fruit FROM Waffle");
			ModifyTypeStmt = connection.prepareStatement("UPDATE Waffle SET type=? WHERE id=?");
			getWaffleByIdStmt = connection.prepareStatement("SELECT * FROM Waffle WHERE id=?");
			deleteWaffleStmt = connection.prepareStatement("DELETE FROM Waffle WHERE id=?");
			getWafflesFromOrderStmt = connection.prepareStatement("SELECT * FROM Waffle w JOIN \"Order\" o ON w.id_order = o.id WHERE id_order = ?");
			deleteWaffleFromOrderStmt = connection.prepareStatement("DELETE FROM Waffle WHERE id_order=? AND id=?");
        }
		catch (SQLException e)
		{
            e.printStackTrace();
        }
    }
    
    Connection getConnection() 
    {
        return connection;
    }
    
    void clearWaffles() 
    {
		try 
		{
			deleteAllWafflesStmt.executeUpdate();
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
    }
    
    public int addWaffle(Waffle waffle)
    {
    	int count = 0;
    	
    	try 
    	{
			addWaffleStmt.setInt(1, waffle.getId_order());
			addWaffleStmt.setString(2, waffle.getType());
			addWaffleStmt.setDouble(3, waffle.getPrice());
			addWaffleStmt.setString(4, waffle.getTopping());
			addWaffleStmt.setString(5, waffle.getSugar());
			addWaffleStmt.setString(6, waffle.getCream());
			addWaffleStmt.setString(7, waffle.getFruit());
			
			count = addWaffleStmt.executeUpdate();
		} 
    	catch (SQLException e) 
    	{
			e.printStackTrace();
		}
    	
    	return count;
    }
    
    public List<Waffle> getAllWaffles() 
    {
		List<Waffle> waffles = new ArrayList<Waffle>();

		try 
		{
			ResultSet rs = getAllWafflesStmt.executeQuery();

			while (rs.next()) 
			{
				Waffle waffle = new Waffle();

				waffle.setId(rs.getInt("id"));
				waffle.setType(rs.getString("type"));
				waffle.setPrice(rs.getDouble("price"));
				waffle.setTopping(rs.getString("topping"));
				waffle.setSugar(rs.getString("sugar"));
				waffle.setCream(rs.getString("cream"));
				waffle.setFruit(rs.getString("fruit"));
				
				waffles.add(waffle);
			}

		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
		return waffles;
    }

	public void modifyType(Waffle waffle) throws SQLException
	{
		try
		{
			ModifyTypeStmt.setString(1, waffle.getType());
			ModifyTypeStmt.setInt(2, waffle.getId());
			ModifyTypeStmt.executeUpdate();
		}
		catch (SQLException e)
		{
			e.printStackTrace();
		}
	}

	public Waffle getWaffleById(Integer id) throws SQLException
	{
		Waffle waffle = new Waffle();
		try
		{
			getWaffleByIdStmt.setInt(1, id);
			ResultSet rs = getWaffleByIdStmt.executeQuery();

			while(rs.next())
			{
				waffle.setId(rs.getInt("id"));
				waffle.setType(rs.getString("type"));
				waffle.setPrice(rs.getDouble("price"));
				waffle.setTopping(rs.getString("topping"));
				waffle.setSugar(rs.getString("sugar"));
				waffle.setCream(rs.getString("cream"));
				waffle.setFruit(rs.getString("fruit"));
			}
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}

		return waffle;
	}

	public int delete(Integer id) throws SQLException
	{
		int count = 0;

		try
		{
			deleteWaffleStmt.setInt(1, id);
			count = deleteWaffleStmt.executeUpdate();
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}

		return count;
	}

	public List<Waffle> getWafflesFromOrder(Integer id) throws SQLException
	{
		getWafflesFromOrderStmt.setInt(1,id);
		ResultSet rs = getWafflesFromOrderStmt.executeQuery();
		List<Waffle> waffles = new ArrayList<Waffle>();
		Waffle waffle = new Waffle();

		while(rs.next())
		{
			waffle.setId(rs.getInt("id"));
			waffle.setId_order(rs.getInt("id_order"));
			waffle.setType(rs.getString("type"));
			waffle.setPrice(rs.getDouble("price"));
			waffle.setTopping(rs.getString("topping"));
			waffle.setSugar(rs.getString("sugar"));
			waffle.setCream(rs.getString("cream"));
			waffle.setFruit(rs.getString("fruit"));

			waffles.add(waffle);
		}
		return waffles;
	}

	public int deleteWaffleFromOrder(Integer id_order,Integer id_waffle) throws SQLException
	{
		int count = 0;

		try
		{
			deleteWaffleFromOrderStmt.setInt(1,id_order);
			deleteWaffleFromOrderStmt.setInt(2,id_waffle);
			count = deleteWaffleFromOrderStmt.executeUpdate();
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}

		return count;
	}
}
